export enum MovieGenre {
  Action = "Δράση",
  Adventure = "Περιπέτεια",
  Animation = "Κιν. Σχέδια",
  Comedy = "Κωμωδία",
  Crime = "Έγκλημα",
  Documentary = "Ντοκιμαντέρ",
  Drama = "Δράμα",
  Family = "Οικογενειακή",
  Fantasy = "Φαντασίας",
  History = "Ιστορική",
  Horror = "Τρόμου",
  Music = "Μουσική",
  Mystery = "Μυστηρίου",
  Romance = "Ρομαντική",
  ScienceFiction = "Επ. Φαντασία",
  TvMovie = "Τηλεοπτική",
  Thriller = "Θρίλερ",
  War = "Πόλεμική",
  Western = "Γουέστερν",
  Unknown = "Άγνωστο Είδος",
}